name: Reusable NodeJS Workflow

on:
  push:
    branches:
      - feature-tst

jobs:
  call-workflow:
    uses: schneider/ra-actions/.github/workflows/build-scan-deploy-nodejs.yml@feature-tst
    secrets:
      #SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      NPM_TOKEN:  ${{ secrets.NPM_TOKEN }}
