name: Reusable NodeJS Workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow:
    uses: schneider/ra-actions/.github/workflows/build-scan-deploy.yml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      NPM_TOKEN: 
